title: jack's dotfiles
description: my personal dotfiles (for macOS)
logo: https://raw.githubusercontent.com/soarnpro/soarn.pro/master/favicon-194x194.png
show_downloads: false
# Theme
theme: jekyll-theme-minimal
# Google Analytics
google_analytics: UA-114243378-
# Plugins
plugins:
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-seo-tag
